name: Daily
main: Daily\Main
version: "1.0"
api: 4.0.0
load: POSTWORLD
author: rayyan
description: Let your players get cooldowned rewards
website: https://github.com/ThatFcesh/Rewards
permissions:
  rewards.command.reward:
    default: true
    description: Permission to use /reward
  rewards.waiting.bypass:
    default: op
    description: Permission to bypass the waiting time
